# Generated by Django 4.2.30 on 2026-06-05 13:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.RESTRICT, related_name='progress_records', to='courses.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress Records',
                'db_table': 'progress',
                'indexes': [models.Index(fields=['student'], name='progress_student_c5357a_idx'), models.Index(fields=['course'], name='progress_course__8a4a63_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['student'], name='enrollments_student_379f04_idx'), models.Index(fields=['course'], name='enrollments_course__711f04_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
