# Generated by Django 4.2.30 on 2026-06-05 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Python Programming', 'Python Programming'), ('Digital Marketing', 'Digital Marketing'), ('Mobile Development', 'Mobile Development'), ('Cybersecurity', 'Cybersecurity'), ('Cloud Computing', 'Cloud Computing'), ('Other', 'Other')], db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.RESTRICT, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='courses_title_0466cc_idx'), models.Index(fields=['category'], name='courses_categor_33f89e_idx'), models.Index(fields=['created_by'], name='courses_created_16fd2d_idx')],
            },
        ),
    ]
