# Generated by Django 4.2.30 on 2026-06-05 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment'], name='submissions_assignm_9eeb28_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student'], name='submissions_student_51a963_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course'], name='assignments_course__383e45_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['deadline'], name='assignments_deadlin_9c956b_idx'),
        ),
    ]
